export default {
	LABEL_FONT_SIZE_SMALL : '0.75rem',
	INPUT_FONT_SIZE : '1rem',
	LABEL_COLOR:'#9896b1',
	INPUT_COLOR:'#3b3a4b',
	INPUT_BORDER_COLOR:'#9896b1',
	DROPDOWN_COLOR:'#333',
	DROPDOWN_BACKGROUND:'whitesmoke',
	DROPDOWN_INPUT_BACKGROUND:'#efedfb',
	DROPDOWN_HOVER_COLOR:'#FFF',
	DROPDOWN_HOVER_BG_COLOR : '#007FFF',
	DROPDOWN_INPUT_SHADOW : '1px 1px 1px 1px #c3c3c3',
	DROPDOWN_SHADOW : '2px 2px 10px 0px #8e8181',
	INPUT_BORDER_WIDTH : '0 0 1px 0'
}