export default {
	FONT_SIZE : '1.1rem',
	FONT_SIZE : '1rem',
	LABEL_COLOR:'#9896b1',
	INPUT_COLOR:'#3b3a4b',
	INPUT_BORDER_COLOR:'#9896b1',
	INPUT_BORDER_WIDTH : '1px',
	DROPDOWN_COLOR:'#333',
	DROPDOWN_BACKGROUND:'white',
	DROPDOWN_HOVER_COLOR:'#FFF',
	DROPDOWN_HOVER_BG_COLOR : '#007FFF',
	DROPDOWN_SHADOW : '2px 2px 10px 0px #d3d3d3',
	INPUT_BORDER_RADIUS : '4px'
}
