export default {
	FONT_SIZE : '20px',
	INFO_FONT_SIZE : '0.8rem',
	LABEL_COLOR:'#9896b1',
	INPUT_COLOR:'#3b3a4b',
	INPUT_BORDER_COLOR:'#9896b1',
	INPUT_BORDER_WIDTH : '1px',
	INPUT_BORDER_RADIUS : '4px',
	HELPTEXT_COLOR:'#007FFF',
	ERRORTEXT_COLOR:'#DF1D1D',
	DEFAULT_GREEN_COLOR:'#008000',
	DEFAULT_BLUE_COLOR:'#007FFF',
	DEFAULT_RED_COLOR:'#DF1D1D',
	INFO_BG_COLOR : 'white',
	INFO_BOX_SHADOW : '1px 1px 8px 0px #c3c3c3'
}