export default {
	LABEL_FONT_SIZE : '1.1rem',
	INFO_FONT_SIZE : '0.8rem',
	LABEL_COLOR:'#9896b1',
	HELPTEXT_COLOR:'#007FFF',
	ERRORTEXT_COLOR:'#DF1D1D',
	DEFAULT_GREEN_COLOR:'#008000',
	DEFAULT_BLUE_COLOR:'#007FFF',
	DEFAULT_RED_COLOR:'#DF1D1D',
	CHECKBOX_BORDER_FALSE : '#6C6D6D',
	CHECKBOX_BORDER_TRUE : '#007FFF',
	CHECKBOX_TICK_COLOR : '#007FFF',
	INFO_BG_COLOR : 'white',
	INFO_BOX_SHADOW : '1px 1px 8px 0px #c3c3c3'
}